module.exports = [
    { "class": "Anti-Personnel Black ICE",
      "name": "Asp",
      "Per": 4,
      "Spd": 6,
      "Atk": 2,
      "Def": 2,
      "Rez": 15, 
      "Effect": "Destroys a single program installed on the enemy Netrunner's Cyberdeck at random"
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Giant",
      "Per": 2,
      "Spd": 2,
      "Atk": 8,
      "Def": 4,
      "Rez": 25, 
      "Effect": "Does 3d6 damage direct to an enemy Netrunner's brain.  The Netrunner is forcibly and unsafely jacked out of their current netrun.  They suffer the effect of all Rezzed enemy Black ICE they've encountered in the Architecture as they leave, not including the Giant"
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Hellhound",
      "Per": 6,
      "Spd": 6,
      "Atk": 6,
      "Def": 2,
      "Rez": 20, 
      "Effect": "Does 2d6 damage direct to the Netrunner's brain.  Unless insulated, their Cyberdeck catches fire along with their clothing.  Until they spend a meat action to put themselves out, they take 2 damage to their HP when they end their turn.  Multiple effects do not stack."
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Kraken",
      "Per": 6,
      "Spd": 2,
      "Atk": 8,
      "Def": 4,
      "Rez": 30, 
      "Effect": "Does 3d6 damage direct to an enemy Netrunner's brain.  Until the end of the netrunner's next turn, the netrunner cannot progress deeper into the architecture or jack out safely."
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Liche",
      "Per": 8,
      "Spd": 2,
      "Atk": 6,
      "Def": 2,
      "Rez": 25, 
      "Effect": "Enemy netrunner's INT, REF, and DEX are each lowered by 1d6 for the next hour.  The effects are not permanent."
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Raven",
      "Per": 6,
      "Spd": 4,
      "Atk": 4,
      "Def": 2,
      "Rez": 15, 
      "Effect": "Derezzes a single defender program the netrunner has rezzed at random, then deal 1d6 damage directly to the netrunner's brain"
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Scorpion",
      "Per": 2,
      "Spd": 6,
      "Atk": 2,
      "Def": 2,
      "Rez": 15, 
      "Effect": "Enemy Netrunner's MOVE is lowered by 1d6 for the next hour.  The effects are not permanent"
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Skunk",
      "Per": 2,
      "Spd": 4,
      "Atk": 4,
      "Def": 2,
      "Rez": 10, 
      "Effect": "Until this program is derezzed, an enemy netrunner hit by this effect makes all slide checks at -2.  Each Skunk can only effect a single netrunner at a time but the effects stack."
    },
    { "class": "Anti-Personnel Black ICE",
      "name": "Wisp",
      "Per": 4,
      "Spd": 4,
      "Atk": 4,
      "Def": 2,
      "Rez": 15, 
      "Effect": "Does 1d6 damage direct to the enemy netrunner's brain and lowers the amount of total NET actions the netrunner can accomplish on their next turn by 1 (min 2)"
    },
    { "class": "Anti-Program Black ICE",
      "name": "Dragon",
      "Per": 6,
      "Spd": 4,
      "Atk": 6,
      "Def": 6,
      "Rez": 30, 
      "Effect": "Deals 6d6 damage to a program.  If this damage would be enough to derezz the program, it is instead destroyed"
    },
    { "class": "Anti-Program Black ICE",
      "name": "Killer",
      "Per": 4,
      "Spd": 8,
      "Atk": 6,
      "Def": 2,
      "Rez": 20, 
      "Effect": "Deals 4d6 damage to a program.  If this damage would be enough to derezz the program, it is instead destroyed"
    },
    { "class": "Anti-Program Black ICE",
      "name": "Sabertooth",
      "Per": 8,
      "Spd": 6,
      "Atk": 6,
      "Def": 2,
      "Rez": 25, 
      "Effect": "Deals 6d6 damage to a program.  If this damage would be enough to derezz the program, it is instead destroyed"
    }
];