module.exports = [
    { "class": "booster",
      "name": "Eraser",
      "atk": 0,
      "def": 0, 
      "rez": 7,
      "effect": "Increase all Cloak checks you make by +2 as long as this program remains rezzed",
      "maxactivations": -1
    },
    { "class": "booster",
      "name": "See Ya",
      "atk": 0,
      "def": 0, 
      "rez": 7,
      "effect": "Increase all Pathfinder checks you make by +2 as long as this program remains rezzed",
      "maxactivations": -1
    },
    { "class": "booster",
      "name": "Speedy Gonzalvez",
      "atk": 0,
      "def": 0, 
      "rez": 7,
      "effect": "Increase your speed by +2 as long as this program remains rezzed",
      "maxactivations": -1
    },
    { "class": "booster",
      "name": "Worm",
      "atk": 0,
      "def": 0, 
      "rez": 7,
      "effect": "Increase all Backdoor checks you make by +2 as long as this program remains rezzed",
      "maxactivations": -1
    },
    { "class": "defender",
      "name": "Armor",
      "atk": 0,
      "def": 0, 
      "rez": 7,
      "effect": "Lowers all brain damage you would receive by 4.  Only 1 copy of this program can be running at a time.  Each copy can only be used once per netrun.",
      "maxactivations": 1
    },
    { "class": "defender",
      "name": "Flak",
      "atk": 0,
      "def": 0, 
      "rez": 7,
      "effect": "Reduces the ATK of all non-black ICE attacker programs run against you to 0 as long as this program remains rezzed.  Only 1 copy of this program can be running at a time.  Each copy can only be used once per netrun.",
      "maxactivations": 1
    },
    { "class": "defender",
      "name": "Shield",
      "atk": 0,
      "def": 0, 
      "rez": 7,
      "effect": "Stops the first successful Non-Black ICE program effect from dealing brain damage.  After stopping this damage, the shield derezzes itself.  Only 1 copy of this program can be running at a time.   Each copy of this program can only be used once per netrun.",
      "maxactivations": 1
    },
    { "class": "Anti-program Attacker",
      "name": "Banhammer",
      "atk": 1,
      "def": 0, 
      "rez": 0,
      "effect": "Does 3d6 REZ to a non-black ICE program or 2d6 REZ to a Black ICE program",
      "maxactivations": -1
    },
    { "class": "Anti-program Attacker",
      "name": "Sword",
      "atk": 1,
      "def": 0, 
      "rez": 0,
      "effect": "Does 3d6 REZ to a Black ICE Program, or 2d6 REZ to a non-black ICE program",
      "maxactivations": -1
    },
    { "class": "Anti-personnel Attacker",
      "name": "DeckKRASH",
      "atk": 0,
      "def": 0, 
      "rez": 0,
      "effect": "Enemy Netrunner is forcibly and unsafely jacked-out of the architecture, suffering the effect of all Rezzed enemry Black ICE they've encountered in the architecture as they leave.",
      "maxactivations": -1
    },
    { "class": "Anti-personnel Attacker",
      "name": "Hellbolt",
      "atk": 2,
      "def": 0, 
      "rez": 0,
      "effect": "Does 2d6 damage direct to the enemy Netrunner's brain.  Unless insulated, their cyberdeck catches fire along with their clothing.  Until they spend a meat action to put themselves out, they take 2 damage to their HP during their turn. Multiple instances do not stack.",
      "maxactivations": -1
    },
    { "class": "Anti-personnel Attacker",
      "name": "Nervescrub",
      "atk": 0,
      "def": 0, 
      "rez": 0,
      "effect": "Enemy netrunner's INT, REF, and DEX are each lowered by 1d6 for the next hour.  The effects are not permanant.",
      "maxactivations": -1
    },
    { "class": "Anti-personnel Attacker",
      "name": "Poison Flatline",
      "atk": 0,
      "def": 0, 
      "rez": 0,
      "effect": "Destroys a single non-black ICE program installed on the Netrunner target's cyberdeck at random",
      "maxactivations": -1
    },
    { "class": "Anti-personnel Attacker",
      "name": "Superglue",
      "atk": 2,
      "def": 0, 
      "rez": 0,
      "effect": "Enemy netrunner cannot progress deeper into the architecture or jack out safely for 1d6 rounds.  Each copy of this program can only be used once per netrun.",
      "maxactivations": 1
    },
    { "class": "Anti-personnel Attacker",
      "name": "Vrizzbolt",
      "atk": 1,
      "def": 0, 
      "rez": 0,
      "effect": "Does 1d6 damage direct to a netrunner's brain and lowers the amount of total NET actions the netrunner can accomplish on their next turn by 1 (min 2).",
      "maxactivations": -1
    }
];